spring:
  profiles:
    active: dev
logging:
  config: classpath:log4j2.yml
debug: false
mybatis:
  type-aliases-package: com.qimiaochong.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

