spring:
  profiles:
    active: dev
logging:
  config: classpath:log4j2.yml
debug: false

## mybatis
mybatis:
  type-aliases-package: com.qimiaochong.common.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
## 分页插件
pagehelper:
  # 1). helper-dialect
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。配置时，可以使用下面的缩写值：
  # oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
  # 特别注意：使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页。
  helper-dialect: mysql
  # 2). reasonable
  # 默认false禁用 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 3). support-methods-arguments
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  # 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。
  support-methods-arguments: true
  # 4). params
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  params: count=countSql
  # 5). auto-runtime-dialect
  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页 （不支持自动选择sqlserver2012，只能使用sqlserver）。
  auto-runtime-dialect: true
## 通用Mapper
mapper:
  mappers:
    - com.qimiaochong.common.base.BaseMapper
  not-empty: true
  identity: MYSQL
  style: camelhump

## shiro
#shiro:
#  userNativeSessionManager: true
#  sessionManager:
#    sessionIdUrlRewritingEnabled: false
#  loginUrl: /login
#  successUrl: /

